changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} on {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* [#{{.Custom.Issue}}](https://github.com/miniscruff/scopie-py/issues/{{.Custom.Issue}}) {{.Body}}'
kinds:
    - label: Added
      auto: minor
    - label: Changed
      auto: minor
    - label: Deprecated
      auto: minor
    - label: Removed
      auto: minor
    - label: Fixed
      auto: patch
    - label: Security
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
custom:
- key: Issue
  type: int
  minInt: 1
replacements:
- path: pyproject.toml
  find: 'version = ".*"'
  replace: 'version = "{{.Version}}"'
- path: "docs/conf.py"
  find: 'release = ".*"'
  replace: 'release = "{{.Version}}"'
